// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: packet.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace ImpelDown.Proto {

  /// <summary>Holder for reflection information generated from packet.proto</summary>
  public static partial class PacketReflection {

    #region Descriptor
    /// <summary>File descriptor for packet.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PacketReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgxwYWNrZXQucHJvdG8SCWltcGVsRG93bipoCgVNU0dJRBILCgdTX0VOVEVS",
            "EAASCgoGU19JTklUEAESCwoHQ19FTlRFUhACEg4KClNfSU5JVExJU1QQAxIK",
            "CgZDX01PVkUQBBIQCgxTX1BMQVlFUkxJU1QQBRILCgdTX0xFQVZFEAZCEqoC",
            "D0ltcGVsRG93bi5Qcm90b2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::ImpelDown.Proto.MSGID), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum MSGID {
    [pbr::OriginalName("S_ENTER")] SEnter = 0,
    [pbr::OriginalName("S_INIT")] SInit = 1,
    [pbr::OriginalName("C_ENTER")] CEnter = 2,
    [pbr::OriginalName("S_INITLIST")] SInitlist = 3,
    [pbr::OriginalName("C_MOVE")] CMove = 4,
    [pbr::OriginalName("S_PLAYERLIST")] SPlayerlist = 5,
    [pbr::OriginalName("S_LEAVE")] SLeave = 6,
  }

  #endregion

}

#endregion Designer generated code
